### ISSUE TITLE
Question about file structure and numbering 

### ISSUE THREAD

**Issue by VallesMarinerisExplorer** [ecotaxa/ecotaxa_back#30]
Hi ecotaxa_back,

I am curious about the file repository structure, particularly how images are organized. I am trying to run an image classification algorithm on some of the collected samples and I am a little confused about what the numbers mean in this url:

https://ecotaxa.obs-vlfr.fr/vault/28365/8850.jpg

I tried reading through some of the API documentation but it is a little unclear how to do this. What do these numbers mean? Is this question better suited for the API page?

**Comment by grololo06** [comment]
Hi,
Sorry for late reply, I'm not monitoring this project too often (except the CI of course :).
These number don't really 'mean' anything, they are just unique identifiers for the images, and in groups of 100K, to avoid having everything in a fat directory.
Maybe I don't get the question...

**Comment by grololo06** [comment]
Feel free to reopen.
