### ISSUE TITLE
File structuring 

### ISSUE THREAD

**Issue by VallesMarinerisExplorer** [ecotaxa/ecotaxa_back#31]
Hi Ecotaxa server,

I am interested in the file structure for images. I would like to make HTTP requests and download images for an automated classifier.

Here is an example path:

https://ecotaxa.obs-vlfr.fr/vault/28365/8854.jpg

What do the numbers mean? It is unclear how to do this with the API, maybe there is a numbering convention.

Thanks

**Comment by jiho** [comment]
I am transferring the issue to the ecotaxa_back repo, in which the API lives.

The numbers don't mean anything specific. 

You want to look at the object api which provides the link to each images: https://ecotaxa.obs-vlfr.fr/api/docs#/object/object_query or https://ecotaxa.obs-vlfr.fr/api/docs#/objects/get_object_set (look at `img_file_name`).

**Comment by jiho** [comment]
If you don't mind my asking, can you please explain why you are interested in those images (the rest of your repos seem quite far from the concern of EcoTaxa).

**Comment by VallesMarinerisExplorer** [comment]
Cool! Thanks for your help. I work for a company and we are developing open-source buoys with planktoscopes on them! We want to demonstrate further usage of the Open Data Cube, a tool to visualize and analyze geospatial data. Want to demonstrate open-source image recognition pipeline in the ODC.

https://www.opendatacube.org/

Thanks for your help!

**Comment by VallesMarinerisExplorer** [comment]
Hi again,

Is there a method to get all of the image paths at once for a given project, organized by species? I want to train a planktoscope image recognition python script using the Ecotaxa data to discern between species. So far, I have been able to get all the images for one particular species using the API. However, this takes a long time because I am using the API to get one object at a time and then correlating the image path to that object. Is there a method that can return all the links to images for a given project, maybe organized by species? Some kind of dictionary object maybe i.e. {"Chlorella": ["9324/18233.jpg", "4248/13434.jpg"], "Karenia Brevis": ["59342/19033.jpg"] }? I want to be able to use the images to understand plankton vertical migration in the water column and also understand biological conditions/levels that would indicate future algae blooms so that response and prevention can be improved.

**Comment by jiho** [comment]
Sorry for the very late reply; the `get_object_set` endpoint with `fields` = `img.file_name` and `txo.display_name` should give you what you need.

**Comment by jiho** [comment]
See https://github.com/jiho/prepare_ecotaxa_datasets/blob/master/1.download_data.py for an example.
