### ISSUE TITLE
bug : import LAT/LON depuis projets uvp6

### ISSUE THREAD

**Issue by ccatalano** [ecotaxa/ecotaxa_back#49]
La latitude et longitude sont modifiées lors de l'import dans ecotaxa depuis un projet uvp6. Le fichier tsv a été créé par uvpapp. Il semble y avoir comme un petit offset.
Ceci a été vu sur un projet et confirmé sur un autre. Vérifié que sur le premier objet.
Info : l'import dans ecopart est bon
![image](https://user-images.githubusercontent.com/59558334/202762189-98a6fb3a-ad52-4da3-8675-333dfde066e3.png)
![image](https://user-images.githubusercontent.com/59558334/202762222-2f4ca019-7fdd-4bd1-97f6-07cdc7158995.png)
![image](https://user-images.githubusercontent.com/59558334/202762294-36cb2891-ceb9-4921-bd88-dbc030f9b42d.png)
![image](https://user-images.githubusercontent.com/59558334/202762447-dfe09a32-f530-43c6-a22c-b08d5e843632.png)

**Comment by jiho** [comment]
Les lat et lon doivent être spécifiées en degrés décimaux, pas en degrés minutes.

Le pb ici est même que le fichier ait pu être importé!

**Comment by grololo06** [comment]
La routine de conversion ne tient pas compte du signe: https://github.com/ecotaxa/ecotaxa_back/blob/5fcd3efc109ba1e277836c43ff64cdd222d81d4e/py/BO/helpers/TSVHelpers.py#L62 C'est hérité du code "historique" mais bon j'aurais dû me méfier (là aussi). 
Effectivement, LN l'a corrigé quand il a fait ecopart: https://github.com/ecotaxa/ecopart/blob/be03edf4b9dd4602614f9f45e73ba446649650ad/py/part_app/tasks/importcommon.py#L14

**Comment by grololo06** [comment]
Euh j'ai vu ce commit et je suis perdu dans l'historique: https://github.com/ecotaxa/ecotaxa_front/commit/65f10b61e55a56ccf2d453f56de2cb4c7528d965 
On dirait que j'avais porté le bug dans le back-end avant qu'il soit corrigé par LN (pour un problème connexe) parce qu'il l'a vu en faisant des tests unitaires (que je n'ai pas portés). Bref, bug confirmé, bien vu.

**Comment by jiho** [comment]
Euh et sinon on pourrait pas juste forcer à une version décimale? C'est ce qui est spécifié dans la page d'import; ce format bizarre n'est documenté nulle part...

<img width="322" alt="Screenshot 2022-11-18 at 21 21 05" src="https://user-images.githubusercontent.com/18445/202795396-4d9cf4d1-ae81-4e5a-b883-c0b3ff6911a4.png">

**Comment by grololo06** [comment]
C'est dû au format produit par UvpApp, mais je vois qu'il y a une issue en cours pour "normaliser": https://github.com/ecotaxa/uvpapp/issues/103

**Comment by ccatalano** [comment]
L'issue uvpapp est plus sur le nomage des images (datetime[...] ) que a évolué ces dernières années et qui doit être pris en compte par les différentes versions d'uvpapp

**Comment by ccatalano** [comment]
@grololo06 as-tu corrigé le bug avec le commit que tu cite ? j'ai réimporté mais rien n'a changé

**Comment by grololo06** [comment]
@ccatalano oui le code est corrigé, mais on n'a pas installé le code en production donc ce n'est pas effectif pour les utilisateurs.

**Comment by ccatalano** [comment]
implémenté et vérifié
