### ISSUE TITLE
Provide a way to upload/process files of unlimited size

### ISSUE THREAD

**Issue by moi90** [ecotaxa/ecotaxa_back#62]
Currently, the HTTP upload file size limit is 500MB. The only alternative is FTP upload, but this is not likely to stay. (Right?) A file size limit is reasonable, e.g. for security reasons. (E.g. fastapi's `UploadFile` receives the whole file, before user credentials are even checked: https://github.com/tiangolo/fastapi/issues/4941 )

Therefore, it would be great to be able to ingest split archives. Then, one could upload several chunks separately and import them as one. There is [split-file-reader](https://pypi.org/project/split-file-reader/) which could be used in `ImportServiceBase.unzip_if_needed`, so that the rest of the import process would be unaffected.

**Comment by moi90** [comment]
A better alternative would be maybe to change the way files are uploaded. If a user `PUT`s to `my_files/{subpath}/{filename}, credentials can be checked before the transfer and the file contents can be written directly to the correct location. A file size limit would then not be needed.

**Comment by moi90** [comment]
@grololo06 @jiho ?

**Comment by moi90** [comment]
It seems that the file size limit could also be enforced by the reverse proxy, not by fastAPI or the application. Is that so?

https://stackoverflow.com/a/68098020/1116842

**Comment by jiho** [comment]
It's in the works. FTP will be gone in favour of a more efficient HTTP-based file management. We tested it for files up to 2+GB and several dozen million files. Should be there in a few weeks.
(And the current limit may actually be higher than 500MB, I think the message in the UI is a bit "conservative").
