### ISSUE TITLE
Several endpoints request a schema but the schema is not referenced

### ISSUE THREAD

**Issue by ThelmaPana** [ecotaxa/ecotaxa_back#71]
In `api/paths/object_set/parents/post/requestBody/content/application/json` there is a `schema`, but this schema only has `title`, `type` and `items`. The `$ref` field found in other schemas is absent, and there is no corresponding schema in `#/components/schemas`.

This is the case for:
- `/object_set/parents`
- `/object_set/`
- `/jobs/{job_id}/answer`

Shouldn't these schemas have a `$ref` like the others?

**Comment by grololo06** [comment]
Hello! 
$ref is only needed (in theory) when the structure is shared b/w several entry points. E.g. MinUserModel.
See https://swagger.io/docs/specification/using-ref/ for more details.
But I see that some blocks, even if used a single time, gave birth to $ref, a bit of mystery.
In the entry points you name, there is most probably nothing shared with others.
